- authorized_key: user=pi key="{{ lookup('file', '/home/bram/.ssh/id_rsa.pub') }}"

- name: Ensure private key and public one are present
  copy: 
    src: "/home/bram/.ssh/{{item}}"
    dest: "/home/pi/.ssh/{{ item }}" 
    mode: 0600
  with_items:
    - 'id_rsa.pub'
    - 'id_rsa'

- name: Disallow root SSH access
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present 
  notify: restart sshd

- name: Disallow password authentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart sshd